apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - prometheus-community-helmrepository.yaml
  - grafana-helmrepository.yaml
  - kube-prometheus-stack-helmrelease.yaml
  - blackbox-exporter-helmrelease.yaml
  - loki-helmrelease.yaml
  - promtail-helmrelease.yaml

