apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../infra/longhorn
  - ../../../infra/metrics-server
  - ../../../infra/pod-report
  - ../../../infra/cloudflared
  - ../../../infra/cloudflare-ddns-ipv6
  - ../../../infra/tailscale
  - ../../../infra/backups
  - ../../../infra/observability
  - ../../../infra/namespaces/wotlk.yaml
  - ../../../secrets/tailscale-auth.enc.yaml
  - ../../../secrets/longhorn-b2-credentials.enc.yaml
  - ../../../secrets/restic-b2-photos.enc.yaml
  - ../../../secrets/grafana-admin.enc.yaml
  - ../../../secrets/wotlk-mariadb-auth.enc.yaml
  - ../../../secrets/cloudflare-api-token.enc.yaml
