apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      serviceAccountName: homepage
      containers:
        - name: homepage
          image: ghcr.io/benphelps/homepage:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: TZ
              value: Australia/Melbourne
          volumeMounts:
            - name: config
              mountPath: /app/config
            - name: logs
              mountPath: /app/config/logs
            - name: app-config
              mountPath: /app/config/settings.yaml
              subPath: settings.yaml
              readOnly: true
            - name: app-config
              mountPath: /app/config/services.yaml
              subPath: services.yaml
              readOnly: true
            - name: app-config
              mountPath: /app/config/bookmarks.yaml
              subPath: bookmarks.yaml
              readOnly: true
            - name: app-config
              mountPath: /app/config/widgets.yaml
              subPath: widgets.yaml
              readOnly: true
            - name: app-config
              mountPath: /app/config/kubernetes.yaml
              subPath: kubernetes.yaml
              readOnly: true
            - name: app-config
              mountPath: /app/config/custom.css
              subPath: custom.css
              readOnly: true
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: homepage-config
        - name: logs
          emptyDir: {}
        - name: app-config
          configMap:
            name: homepage-app-config
