apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wow
resources:
  - namespace.yaml
  - data-pvc-rwx.yaml
  - client-files-pv.yaml
  - mariadb-pvc.yaml
  - mariadb-statefulset.yaml
  - mariadb-service.yaml
  - db-migrate-cronjob.yaml
  - client-extract-cronjob.yaml
  - realmd-deployment.yaml
  - realmd-service.yaml
  - mangosd-deployment.yaml
  - mangosd-service.yaml
