apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wow
resources:
  - namespace.yaml
  - mariadb-pvc.yaml
  - mariadb-statefulset.yaml
  - mariadb-service.yaml
  - server-deployment.yaml
  - server-service.yaml
