apiVersion: v1
kind: ConfigMap
metadata:
  name: wotlk-authserver-config
data:
  authserver.conf: |
    [authserver]
    LogsDir = ""
    BindIP = "0.0.0.0"
    RealmServerPort = 3724
    LoginDatabaseInfo = "${DB_HOST};${DB_PORT};${DB_USER};${DB_PASSWORD};${DB_AUTH_DB}"

    # Authentication settings
    StrictVersionCheck = 0
    AllowLoggingIPAddressesInDatabase = 1

    # Update settings
    Updates.AllowRehash = 1
    Updates.ArchivedRedundancy = 0
    Updates.CleanDeadRefMaxCount = 3

    # TOTP settings
    TOTPMasterSecret = ""

    # IP Location settings
    IPLocationFile = ""

    # Realm settings
    RealmsStateUpdateDelay = 20

    # Network settings
    Network.UseSocketActivation = 0
    EnableProxyProtocol = 0

    # Process settings
    PidFile = ""

    # Database settings
    LoginDatabase.WorkerThreads = 1
    LoginDatabase.SynchThreads = 1

    # MySQL settings
    MySQLExecutable = ""

    # Update settings
    Updates.Redundancy = 1

    # Process settings
    UseProcessors = 0
    ProcessPriority = 0

    # Network settings
    MaxPingTime = 30

    # Logger settings
    Logger.root = 4,Console Auth
