apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-config
  namespace: immich
data:
  # Database
  DB_HOSTNAME: "immich-postgres"
  DB_PORT: "5432"
  DB_DATABASE_NAME: "immich"
  DB_USERNAME: "postgres"
  # Redis
  REDIS_HOSTNAME: "immich-redis"
  REDIS_PORT: "6379"
  # Immich settings
  UPLOAD_LOCATION: "/usr/src/app/upload"
  IMMICH_MACHINE_LEARNING_URL: "http://immich-machine-learning:3003"
  # Timezone
  TZ: "Australia/Melbourne"
