apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: immich

resources:
  - namespace.yaml
  - nfs-pv-uploads.yaml
  - nfs-pv-model-cache.yaml
  - pvc.yaml
  - configmap.yaml
  - postgres.yaml
  - redis.yaml
  - server.yaml
  - machine-learning.yaml
