apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: wotlk-worldserver-config
    files:
      - worldserver.conf=worldserver.conf
      - playerbots.conf=playerbots.conf
      - mod_ahbot.conf=mod_ahbot.conf
