---
title: cooked.beer // Mission Control
theme: dark
color: violet
headerStyle: boxedWidgets
hideVersion: true
useEqualHeights: true
statusStyle: badge

background:
  image: /assets/998981.jpg
  opacity: 34
  blur: sm
  saturate: 135
  brightness: 110
cardBlur: lg

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  mobileButtonPosition: bottom-right

providers:
  longhorn:
    url: http://longhorn-frontend.longhorn-system.svc.cluster.local

layout:
  Mission Control:
    style: row
    columns: 3
  Media Stack:
    style: row
    columns: 3
  Game Worlds:
    style: row
    columns: 3
  Security & Access:
    style: row
    columns: 3
  Storage & Cluster:
    style: row
    columns: 2
  Personal:
    style: row
    columns: 3
