apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tailscale

resources:
  - namespace.yaml
  - rbac.yaml
  - deployment.yaml
  - deployment-wow.yaml

# IMPORTANT: keep ConfigMap names stable so the Deployment mount always matches
generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: tailscale-serve-config
    files:
      - serve.json
  - name: tailscale-serve-config-wow
    files:
      - serve.json=serve-wow.json