apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sparkyfitness

resources:
  - namespace.yaml
  - postgres.yaml
  - server.yaml
  - frontend.yaml
  - ../../secrets/sparkyfitness.enc.yaml

