apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - infrastructure/infrastructure-kustomization.yaml
  - infrastructure/observability-config-kustomization.yaml
  - apps/apps-kustomization.yaml
  - apps/arr-kustomization.yaml
  - apps/homepage-kustomization.yaml
  - apps/wow-kustomization.yaml
  - apps/wotlk-kustomization.yaml
  - infrastructure/longhorn-node-disks-kustomization.yaml
