apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - ../../secrets/cloudflared-credentials.enc.yaml
configMapGenerator:
  - name: cloudflared-config
    namespace: cloudflared
    files:
      - config.yaml=config.yaml
